subito:
  environment: svil

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subito
  jpa:
    properties:
      hibernate:
        default_schema: subito
        show_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      topic: topic-orders
      group-id: subito
  liquibase:
    enabled: true
    changelog: config/liquibase/master.xml
    schema: subito

logging:
  level:
    root: INFO

server:
  port: 8081
  servlet:
    context-path: /progetto-subito
